language: node_js
node_js:
  - '7'
  - '8'
  - '9'
cache: 
  yarn: true
before_script:
  - npm run build 
deploy: 
  skip_cleanup: true
  provider: npm
  email: vandeurenglenn@gmail.com
  api_key:
    secure: J7keI+EiOcHs9CfHQz/E246oD787r6QuuSda6YMqQeMBNLwbkWp/jcUUbO0FmTsgCJbopdYpXS6kKYBM2LYNhhqwtOzdpgTlkw6JswDvb/tyHs5pVzJ7vUPDiaRsapFytzUT/8euRpN7gxAB023I4As06YmAWxy+tExZZXGcB2i6UoH217O2O5S9MrNiZyhagX908tDz4CAtpKRtKWmG9sj6K5w5xwnof2MBuKQHELx54/45GBrS3kWfpqd+ugJrcER2kTBiad7ku3/V1GwEUd4TqdUB6GImGYFBMKxSCQf+zdfS6v8DH+UyYjtLA3pHcDYqeWbUKp17+f9wgYxnMcoE2VWGm1H5zkrloZStT86aawkfN8EJ8MrvcKLLa0zeK14UwPxctvL/Pguk5DrLhRgRSmqX2/RFkw0YzaJX3iWl1TbVd9E59n1ctOYqTjtmhtVe9qtS4H+qrqKaYBUYUmnS2XiNVurwmg0YJJuznnq5SXPSBE7AGi7YOU+4RDRCrmSrtKMWz1nRrIezR/Pax4y0R+3t6vah4mclSuUiUJloR14dCllyTQE35vIYjMvoAhcQeDJVugvwNG0Zmas1qZwvSvDhYMA6xA9s3FzpU3LRgvmPPxJT4l8Dh/Lp4tsTUG2W50gm4P4WtfcN2bl/IeOkOt/t/e+Yj+fqcxDr1cI=
  on:
    tags: true
    repo: leofcoin/leofcoin-core
